### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by erfur** [ituis18/a1-erfur#1]
requirements for HTML:
- [x]	html5 standart
- [x]	use of <body> <heading> <paragraph> tags
- [x]    correctly formatted itemized or enumerated list
- [x]    correctly formatted multi-level list
- [x]    correctly formatted HTML table
- [x]    an image
- [x]        alternative text, width, height
- [x]    hyperlinks
- [x]    more than one web page with hyperlinks between
- [x]    text styles
- [x]        font family
- [x]        font size
- [x]        bold/italic
- [x]        alignment
- [x]        color
- [x]    non-text styles
- [x]        background changes
- [x]        borders
- [x]        table
- [x]        list formatting
- [x]    structured and styled using grouping elements

images:
- [x]    images spatially transformed using GIMP or Inkscape
- [x]    enhanced or color-transformed by GIMP
- [x]    images that have had drawing applied to them using GIMP
- [x]    images that have been manipulated using selections in GIMP
- [ ]    basic shapes or paths added by Inkscape
- [ ]    images that have had formats added to shapes or paths in Inkscape
- [x]    repository to contain both original and manipulated images

CSS:
- [x]    "classes" to style elements [done]
- [x]    included both as an external style sheet and a style attribute
